version: '3.8'

services:
  arangodb:
    image: arangodb:3.12
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASS}
    ports:
      - "${ARANGO_PORT}:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps:/var/lib/arangodb3-apps

volumes:
  arango_data:
  arango_apps:
